#!/bin/sh
DB_USER="${MONGODB_USERNAME:-mongodb}"
DB_PASSWORD="${MONGODB_PASSWORD:-mongodb}"
DB_NAME="${MONGODB_DBNAME:-admin}"
DB_STORAGE_ENGINE="${MONGODB_STORAGEENGINE:-mmapv1}"
DB_JOURNALING="${MONGODB_JOURNALING:-nojournal}"
DOCKER_DB_PORT=27017
DOCKER_DB_MOUNTPOINT="/data/db"